
meta_product_name: "Damien Guillot"
meta_title: "Damien Guillot - Photography & Videography"
meta_description: "Let me tell your story."
meta_image: "Leonard-Cohen-compressor.jpg"                       # should exist in `app/assets/images/`
